- id: gha-docs
  name: gha-docs
  description: Generate documentation for GitHub Actions workflows.
  entry: gha-docs generate -w .github/workflows -o .github/workflows/_workflows.md
  language: 'golang'
  pass_filenames: false
  files: .github/workflows
  exclude: .github/workflows/_workflows.md