name: Run unit tests
# This is a comment but not a description

## This line should not be included as description
## Because it doesn't start from the first line

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "Running tests"
